### PR TITLE
Meshtextured : media plugin to handle 3D textured obj zip files

### PR DESCRIPTION
**Pull request by gautiermichelin**
Hi Seth & Stefan,

capture d ecran 2014-11-02 a 09 51 48

This is the pull request I've talked on with Stefan (not having accepted it in any kind, only kept informed). 
This is a media plugin handling .obj.zip files as a container having obj, mtl and texture files inside.
It currently realizes a preview through blender (external app defined) & a conversion through three.js obj2utf8x script.

I've made my tests with sketchfab and autodesk 123D catch obj files. Those downloaded need only to be renamed .obj.zip. I've chosen not to catch all zip files containing obj, to be sure not to impact too much elsewhere.

What is to be done now :
- the three.js viewer is ok when opening an object, go to media view and clicking on a representation, not on the left infobox (but calling /index.php/editor/objects/ObjectEditor/GetRepresentationEditor/object_id/5/representation_id/10 is ok, weird)
- the viewer UI is minimalistic, I intend to make top, bottom, left... buttons. Everything done with a mouse should be available from buttons for a maximal accessibility.
- blender preview rendering background (darkgray) could be lighter, maybe configurable by end-users

How to activate :
- install blender and set its path inside external applications conf
- install obj2utf8x (I've included executables for windows and my mac compiled version too) and set its path inside external applications conf

### CODE REVIEW

**Comment by gautiermichelin** [comment]
Small bottom note : this project is not abandoned, I plan to revive it in march.

**Comment by skeidel** [comment]
Closing this for now. Let us know if/when you have a new version.

**Comment by xcelspreadsheet** [comment]
A few years late, but just wondering if there's been any development on a viewer for textured 3D meshes.

**Comment by collectiveaccess** [comment]
No, it only supports surfaces. It you need textures file an issue for it on our JIRA (https://collectiveaccess.atlassian.net) and we'll see about adding it to the development queue.

**Pull request closed without merging**
