### PR TITLE
Search add existing media

### PR DESCRIPTION
**Pull request by naeemmuhammad**
Adding existing media representations in objects is not working. When searched for an existing media representation a list of existing media shows up correctly, however making a selection and saving object does not add the selected media representation to the object. This fix solves this problem.

### CODE REVIEW

**Comment by SethKaufman** [comment]
Hi,

It uses http. It’s just a web service. Details are here: http://eol.org/api

The URL we’re using is in the form http://eol.org/api/search/1.0.json?q={search}&page={page}
For example http://eol.org/api/search/1.0.json?q=canis&page=1

**Comment by naeemmuhammad** [comment]
I was wondering if there is any consideration about this issue and this pull request.

**Comment by collectiveaccess** [comment]
It's against master, which doesn't see active development. Resubmit it against develop and we'll look at it.

**Comment by naeemmuhammad** [comment]
have you fixed this issue yourself in newer version?

**Comment by collectiveaccess** [comment]
No

**Comment by naeemmuhammad** [comment]
Thanks

**Comment by naeemmuhammad** [comment]
check: https://github.com/collectiveaccess/providence/pull/342

**Pull request closed without merging**
