### PR TITLE
NOJIRA : allows to hook TimeExpressionParser preprocess

### PR DESCRIPTION
**Pull request by gautiermichelin**
This allows me to develop into a plugin a preparser for French Revolutionary Calendar dates.
The plugin would allow me to parse dates like "12 thermidor an II" (https://en.wikipedia.org/wiki/French_Republican_Calendar) before sending a normal date to the TEP class. This is only for input now.

In the future, it would allow the development of plugins for date entering from Hebrew, Islamic, persian, chinese calendars, probably with a special text mark to distinguish the calendar if the month names don't help. Going through plugins seems me a prudent way of digging into those.

### CODE REVIEW

**Comment by skeidel** [comment]
Are you sure you want to do this *after* the preprocess function has mangled the input to pieces? I'd do it before (or add hooks for both, I guess?).

**Comment by gautiermichelin** [comment]
Hi Stefan,

I'm better with doing this after, so ordinals like "1er" are treated ; 
accents, capitals are removed ; wordsWithSpaces are handled, and so on.
But I'm ok with doing both hooks naturally.
I'm adding this fast and commiting back.

Gautier

**Comment by gautiermichelin** [comment]
done with 2 hooks, 1 before, 1 update, named in consequence.

**Comment by gautiermichelin** [comment]
Thanks.

**Pull request merged**
