### PR TITLE
Allow adding exporter worksheets without dnd

### PR DESCRIPTION
**Pull request by raboof**
I haven't checked it still works with dnd.

After uploading, the table is not refreshed, but I'm not sure whether
that worked before either ;).

Probably needs some styling as well.

Kept it as draft for now because of the above issues, but feedback welcome!

### CODE REVIEW

**Comment by collectiveaccess** [comment]
What problem is being solved here? I don't recall the motivation... sorry.

**Comment by raboof** [comment]
> I don't recall the motivation... sorry.

No worries, we haven't discussed this before ;)

I noticed the only way to upload a new exporter worksheet is currently via drag-and-drop. That is not always convenient: I didn't happen to have a window to 'drag from' open, and more generally users with particular accessibility preferences/needs might not have drag-and-drop easily available.

So I figured it'd be nice to give the option of uploading files with the standard file selection dialog as well, aside from drag-and-drop.

What do you think?

**Comment by collectiveaccess** [comment]
That's a really good idea. It has always bothered me that drag-and-drop was the only way. We'll need to do it for importer mappings as well though :-/

**Comment by collectiveaccess** [comment]
PS. I'll take a look at this, fix up styling and merge.

**Comment by collectiveaccess** [comment]
This is still on the todo list...

**Comment by raboof** [comment]
thanks for the update, no rush ;)

**Pull request closed without merging**
