### PR TITLE
Add editorconfig configuration, based on Wordpress with very few tweaks.

### PR DESCRIPTION
**Pull request by miceno**
Feel free to comment on it.

It includes configuration for PHPStorm code styling.

### CODE REVIEW

**Comment by collectiveaccess** [comment]
In general I'm fine with this, except for using spaces for indents. We've generally been "tab oriented" We'll test this out for a bit before it is accepted and see how it goes. 

Thanks!

**Comment by miceno** [comment]
Sure!

The tab thing... I changed spaces to tabs in PHP, but left the other file types as they were. I will prefer spaces since they are more reliable, but files are bigger with them :(

Regards.
--
“If you think it's expensive to hire a professional to do the job, wait until you hire an amateur." - Red Adair

**Comment by collectiveaccess** [comment]
Ok great. This sounds good to me.

**Comment by miceno** [comment]
Hi again.
Should your consider merging this PR or should I close it?
Regards.

**Comment by collectiveaccess** [comment]
Sorry, we never got round to trying it. I'll make time this week to evaluate.

**Comment by miceno** [comment]
No problem! 👍 

It was just that it was there and I would like to move forward on the styling, I would like to make sure every new commit I contribute is in the proper styling 😉

**Comment by collectiveaccess** [comment]
Thanks!

**Comment by collectiveaccess** [comment]
Fingers crossed :-)

**Pull request merged**
