### PR TITLE
PROV-2724 Propagate dryRun to data importer

### PR DESCRIPTION
**Pull request by miceno**
It solves https://collectiveaccess.atlassian.net/browse/PROV-856 and https://collectiveaccess.atlassian.net/browse/PROV-2724.

### CODE REVIEW

**Comment by collectiveaccess** [comment]
Thanks for this. Have you tested dry run in the user interface (not command line)? We've seen issues with dry run being run from there where it doesn't work, even though it's being set properly. In those cases it appears to be an issue with transaction handling.

**Comment by miceno** [comment]
I tested it on the command line and on the UI, but not thoroughly, I tested it for my main use case, with the following command line (same on the UI):

`php7.2 bin/caUtils import-data --source ~/incoming/input-data.xlsx  --mapping import-mapping -f XLSX -d DEBUG --dryrun -t import-set`

**Comment by collectiveaccess** [comment]
What version of MySQL are you running?

**Comment by miceno** [comment]
MySQL 5.5.60

**Pull request merged**
