### PR TITLE
NOJIRA : Disabling cli colors under windows

### PR DESCRIPTION
**Pull request by gautiermichelin**
Color are not handled under Windows : http://d.pr/i/1l2sU
capture d ecran 2015-07-30 a 20 55 51

### CODE REVIEW

**Comment by skeidel** [comment]
You may want to use the [OS family helper](https://github.com/collectiveaccess/providence/blob/master-fix/app/helpers/utilityHelpers.php#L472) we already have instead?

**Comment by skeidel** [comment]
Or [this one](https://github.com/collectiveaccess/providence/blob/master-fix/app/helpers/utilityHelpers.php#L488)

**Comment by gautiermichelin** [comment]
Sure.

**Comment by gautiermichelin** [comment]
Done with the first one.

**Pull request merged**
