### PR TITLE
PROV-2724 Propagate dryRun to data importer.

### PR DESCRIPTION
**Pull request by miceno**
Propagate dryRun parameter to the data importer. 

See JIRA issue: https://collectiveaccess.atlassian.net/browse/PROV-2724

### CODE REVIEW

**Comment by collectiveaccess** [comment]
You really should be working with develop branch code. Most/all of these issues are already fixed there. We haven't had the time to wrap them into a release yet though.

**Comment by miceno** [comment]
No problem. The point is that I started to try CA on the current 1.7.8 release, I would not like to deploy a site on the development branch, it will not be safe and things may break.I started with the master branch since it is the one from where releases are created.Do you have any guide on how to use the existing branches and the release process?Regards.On Jan 1, 2020 15:13, CollectiveAccess <notifications@github.com> wrote:You really should be working with develop branch code. Most/all of these issues are already fixed there. We haven't had the time to wrap them into a release yet though.

**Comment by collectiveaccess** [comment]
That develop branch code is basically the next release. We have been using for all of our projects for a while now. We can make it the release this month, especially if you want to help us get it ready :-)

One of the main things left is updating the testing framework for PHPUnit 8.5 (we've been stuck on an ancient version) and validating it with PHP 7.3 and MySQL 8. The testing work is still very much in progress, but the 7.3/MySQL 8 work should be done at this point. I run it with these versions now and haven't had problems.

**Comment by miceno** [comment]
Hi again!

I had a look at the `develop` branch (or should I use `host/develop`?), but this issue is not solved, and it is referred in two different JIRA issues (thank you for giving me access to JIRA 👍 ): https://collectiveaccess.atlassian.net/browse/PROV-856 and https://collectiveaccess.atlassian.net/browse/PROV-2724.

I will branch from `develop` and create a new PR. I am closing this for now.

**Comment by collectiveaccess** [comment]
Host/develop is used for our hosting environment. Use develop only.

I think the dry run issue is actually a problem with transaction handling, not a ui issue. And we’ve had complaints with develop as well as the current release. I’m looking into it.

My comment about using develop rather than master referred to other issues like the missing php tag you noted in master.

**Comment by collectiveaccess** [comment]
Yes perfect. Thanks very much for helping with this.

**Pull request closed without merging**
