### PR TITLE
NOJIRA : add representation through ItemService WebService

### PR DESCRIPTION
**Pull request by gautiermichelin**
Hi @skeidel  & @SethKaufman 

This PR implements addRepresentation to ca_objects through Web Services (ItemService).
I'm bringing it to allow representation upload through my Titanium mobile app for ipad (called Newport, I thought a Rhode Island city name could be a tribute to Seth huge work).

This is fairly working through my tests, this is a early pull request to have your look inside this piece of code, and see if this could manage to go to the master branch in the future.

Syntax for the body request to http://providence.dev/service.php/item/ca_objects/id/14 is this one :
````json
{
    "intrinsic_fields" : {
        "idno" : "TEST-123",
        "type_id" : 24
    },
    "preferred_labels" : [
        {
            "locale" : "en_US",
          "name" : "test 1"
        }
    ],
    "add_representations" : [
      {
        "filename" : "icon.jpg",
        "media_content" : "/9j/4AAQSkZJRgABAQAAAQABAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gOTMK/9sAQwACAgICAgECAgICAwICAwMGBAMDAwMHBQUEBggHCQgIBwgICQoNCwkKDAoICAsPCwwNDg4PDgkLEBEQDhENDg4O/9sAQwECAwMDAwMHBAQHDgkICQ4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4O/8AAEQgAMAAwAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A/Xjxv8f9P8MfGq28BaL4dk8Ta29tNPM/9oR2sMXkmIOm4hiWHnxnGO5xnBxNa/FXxzqCKbbwLolsT/z8eJ5mI/BLMj9a+YfjzZQeGP2/PDmtL8raleQbyScLHNA9qVHYbpmibnGdnqBXc6X4p8cWvihrOLwxoSaX5pW3vb/xa1vJMvZvKW0fB9t341uoxtcxcnex9C22v/EvUFULaeHtMyeSpubn+ax10VvY/EKWESXHinSISeSkXh9z+puf6Vw2ieL7eOaK31HxR4TttQlDGK0h1cSuAoyxGSpfGRnCjFegWesNckNHr0Nyp7WmmvIPzBNZNq9kaK/U3tHmvXsp7fUZo7m7t5vLeaOLy1kBVWDbcnH3sde1a9c5ausPj6WMB8XliJAWBABibB4PQkSrx/s+xro6Q0fAX7b9nd2OneFvFNlGXe0t5ZpChCszWk0VxFGD6sxOB3xjvWnryeDNO1PSfETt8PtDmvrUJFq/iqyjkubhB86pG7PGzqA+du/jd05r1f8Aao0KDVv2X31CeHzotI1GK7lABJKENEVwOoLOnHtXgnwx8Qardfsj+CbqLX7Tw7qFhANN1G7utOa83Pas9pIqKJEwxkiBDfMMcbTkEax1iZy0Zq+LNavNZ+HsNx4a8eadd+INHnF9pTeFfAt5KC6qVeMPHJNw6M68Y6jpjNdJ4C+JfxTuvh/Z6v8A2FqPjnQ5UP2i40/SpdN1OzcH50a3nULNjGNyHewwQgzVT+2dTn1BYo/HvxK1WRsfuNE8F28Fvk56TTWGB06+d+Ndb4H8N3+manfG28IeOWtLt/OZta8XRQR+bjr5dtdsAG4yPLHQcV8pmmQYPMqyxF5U60VZVIO0kuz3Ul5ST8rHq4THSw0XTlCM4PdSX5NWa+T163PQPDnxF8N+LNe0mTRdTZ9U0+58vUdOvswX0SurKwkhkw6lSytjGcLXuKOkibkYOvqDXztr/wANF8VeHdQHiTwVo+i3qWzNpWsad4guLzUoJznBErQRMgHynAkYMeCCOur4W8BeN7Lxf4W1ez+KF7eeCIYzcyaTf6fG93ciSLCRSXAxuRd24YRTkDJNeZhf9ZsDiIUcQo4ii3bnXuTiu8ovSS84u7fRHbUhldeDnRm6ckr8stU/KMkuvmkvM634s2dtrf7N3jjSSySXEujTvbxtzmZEMkf/AI+q1+dvwa8e2vh2K10a7lV9O1WFb+xbzgrvKQI7kxlyFdfNjldlBDKSSN4kxH+iPj7w7qN7oE93oshF4qHMJPyye1fBOifAvVde+C6eC/FPgm9aTS9SlfR7m1uBDJbpkMsiyA5Vt5c46YODwSK+8i0j56SufX/hvV7TWPD9lqVlL51rcRh4274PYjsQeCOxBFegWd0rMqq3yDqa+T/AfwL+MHhS2Npo/iwWWlvIXlh1GIXDPweSPuhsnJZApY43bsDHs9l8IPGVxEBr3xEvpQeq2Si22/Qx4NW3ESTPbLm6tf7FPmXEaYHdxVDwZfQXfhW4gguFulsr6a38xWDKRu3qAR6K6r+FcDB8CvCToP7bnvvET5zu1G5aY/m2TXq+jaNp2gaBBpelW62tlCMRxL0UVlpYvW5//9k=",
        "primary" : "true"
      },
     {
        "media_path" : "http://www.collectiveaccess.org/sites/all/themes/collectiveaccess/img/body_logo.png",
        "primary" : "false"
     }
    ]
}
````

It brings the usual base64 overweight to the request, but everything is sent in the body.

Wishing you a sunny sunday,
Bye,

Gautier

### CODE REVIEW

**Comment by skeidel** [comment]
Why so complicated? You can already add media by using PUT requests to the item service (ca_object_representations table) and passing either a local media path (/data/foo/bar.tiff) or a URL (http://mysite.org/foo/bar.tiff, if pulling media from URLs is enabled in app.conf) to the intrinsic 'media' field.

I [just implemented](https://github.com/skeidel/alhalqa-erzaehlbox/blob/master/upload.rb#L29) a Ruby script for a kiosk-like app one of my clients is going to run in an exhibition yesterday. 

I am on board with adding support for inline base64-encoded media; that could come in handy when dealing with mobile apps where uploading to the server or accessing via http[s] is not an option, but I would want to steer away from the "addRepresentation" hack.

**Comment by skeidel** [comment]
Also, rather than hacking up the ItemService to deal with the base64-string-to-tmp-file stuff, we should do it in the media processing code (BaseModel::_processMedia()) so that that functionality is available to anyone who wants to script things, and not just via services.

**Comment by gautiermichelin** [comment]
Thanks for you script, this is what I'm looking for.

I missed the point of the media intrinsic field for representations. I usually used through addrepresentation method when I did custom import php script, that's what I was searching here :-(

OK for the base64 into BaseModel::_processMedia(), but I don't think I need it anymore, now going your example way.

I'm not quite happy with scp part to send the media to the server, my objective was to do the upload through http requests only. I could have a script of my own saving the posted file to the server (pluging a dedicated file at the root of providence and using CA authentication helpers). Do you think this should done inside CA, inside ItemService for ca_object_representations with a form/multipart request ?

**Comment by skeidel** [comment]
Well knock yourself out. It should still be as easy as possible to craft these requests, obviously. And ideally it would just be one request for the file and the representation data. 

The SCP upload version worked for my project but I get why you would not want to do that.

**Comment by gautiermichelin** [comment]
Hi again @skeidel 

I saw that the detection of the content is done inside BaseJSONService ; it checks if raw posted data (through php://input inside RequestHTTP). Using multipart form encoding inside Postman for my tests, I get posted files encoded inside the php://input.

Solution could be to rely on a multipart decoder inside RequestHTTP , like this one :
https://gist.github.com/jas-/5c3fdc26fedd11cb9fb5#file-stream-php
(there are 2 versions on the page, one function and one in a class form), decider() and file_stream() contain the interesting parts.

My idea is to add 2 methods to RequestHTTP : 
- one getSourcePostData : would return back full raw post if not inside a multipart form ; if inside a multipart form would return the source that has the field name "source"
- one getMultiformNonSourcePostData : would return back an array of uploaded files content. For me at this step, I don't write anything into temp

And then inside ItemService : 
````php
$vs_post_data = $this->opo_request->getRawPostData();
		if(strlen(trim($vs_post_data))>0){
			$this->opa_post = json_decode($vs_post_data,true);
			if(!is_array($this->opa_post)){
				$this->addError(_t("Data sent via POST doesn't seem to be in JSON format"));
			}
````
Instead of directly throwing the error, I would check getSourcePostData() content.

Inside the source JSON, the media intrinsic field content would take a simple string, referring to the name of the var containing the file uploaded. If I have same values, saving is done inside temp dir, and representation media is handled with the file path to the temp file.

Problem is not for me at the end, but inside the RequestHTTP additions : it's very at the core of CA. I'm ok to digg inside and willing too, but don't want to lose your time and mine if you have other ideas.

Do you have any other (and better) way of doing it I've not seen ?

Gautier

**Comment by skeidel** [comment]
Hmm ... I think PHP should take care of decoding the request? I don't think you have to change RequestHTTP. If you send files in a multipart request, they should be available in $_FILES, no? See [here](http://php.net/manual/en/features.file-upload.post-method.php)

We could add some useful accessors for that in RequestHTTP. Also, the raw post data accessor we have right now should probably not include the multipart/form-data segments. No idea if they ever make it to php://input but if they do, we should filter them out.

**Comment by deploiement-ideesculture** [comment]
Inside RequestHTTP we take php://input. The multipart/form comes inside the flux. Note that if I send files in a multipart request, they are only handled inside $_FILES if we are inside a POST request within PHP, not there for a PUT request (see http://stackoverflow.com/questions/9464935/php-multipart-form-data-put-request, first answer, can't find here directly in the documentation but have been blocked by that in the past), that's why parsing php://input is the only way.

I have something working quite well here. 

I'll make a pull request in a pair of hours to catch your eyes on, so you can see how I've handled the thing, and tell me if it could be a way to do it.

**Comment by gautiermichelin** [comment]
(edit : commenting from a deployment profile is not a good idea for archiving)

Inside RequestHTTP we take php://input. The multipart/form comes inside the flux. Note that if I send files in a multipart request, they are only handled inside $_FILES if we are inside a POST request within PHP, not there for a PUT request (see http://stackoverflow.com/questions/9464935/php-multipart-form-data-put-request, first answer, can't find here directly in the documentation but have been blocked by that in the past), that's why parsing php://input is the only way.

I have something working quite well here. 

I'll make a pull request in a pair of hours to catch your eyes on, so you can see how I've handled the thing, and tell me if it could be a way to do it.

**Pull request closed without merging**
