### PR TITLE
viaf support as information service

### PR DESCRIPTION
**Pull request by naeemmuhammad**
This pull request contains an implementation that provides support for searching VIAF content and importing them into Collective Access.

### CODE REVIEW

**Comment by collectiveaccess** [comment]
Thanks for this. Can you please submit this pull request on the develop branch? In general all pull requests should be against develop.

**Comment by naeemmuhammad** [comment]
@collectiveaccess i changed the branch from master to develop in the same pull request, does this work or should i make another pull request?

**Comment by collectiveaccess** [comment]
That's fine.

**Comment by collectiveaccess** [comment]
Oh wait... you're merging master into develop... not good. I'll merge your code directly. Don't do another pull request.

**Comment by collectiveaccess** [comment]
Merged by hand

**Pull request closed without merging**
