### PR TITLE
Add rank to site pages

### PR DESCRIPTION
**Pull request by Monica-Wood**
Enable the ability to sort menu items, or content pulled into other pages.

### CODE REVIEW

**Comment by collectiveaccess** [comment]
What exactly is this needed for?

**Comment by Monica-Wood** [comment]
So you can determine the order that pages show up.  Currently you can only show them based on the the order they are created.  If you create a new one and need it to show between 2 existing, then you can't set this.
Examples are generated menus, or in my case I am generating cards on the front page (and I will also create index pages for other page types) with media and blurb that link off to the full content page.

**Comment by collectiveaccess** [comment]
The pages are accessed by URL on the front-end. There is no order. I guess you're using these on the back-end in a menu?

**Comment by Monica-Wood** [comment]
I am using php code to collect all site pages of a certain template and outputing the media and first bit of the page content into a bootstrap card. This then links off the page itself.   But I cannot control the exact order these pages are returned, this allows to put a 'sort' => 'rank' into the find call.  

Here is the top snippet from my code I am using in Pawtucket on the front_page_html.php

```
$t_site_templates = new ca_site_templates(array("template_code" => "About_Collection_Page"));
if($vn_collection_template_id = $t_site_templates->get("ca_site_templates.template_id")){
        $q_collections = ca_site_pages::find(array('template_id' => $vn_collection_template_id), array('returnAs' => 'searchResult', 'sort' => 'rank', 'checkAccess' => $va_access_values));
        if($q_collections->numHits() > 0){
	        $va_collections = array();
	        while($q_collections->nextHit()){
```

It can also be used to generate menus that link off to site pages created, so admins don't have to add new menu links every time a page is made.  It allows for dynamic creation of content.

**Comment by Monica-Wood** [comment]
Is there anything you would like me to change to have this accepted?

**Comment by Monica-Wood** [comment]
Thank you

**Pull request merged**
