### PR TITLE
Allow additional arguments for ImageMagick external applications

### PR DESCRIPTION
**Pull request by miceno**
Define a configuration item in `external_applications.conf`, like this: `imagemagick_<COMMAND_NAME>_args` per command.

For example, for `convert` command, use 

```
imagemagick_convert_args = -limit thread 1
```

As of now it only allows arguments on the ImageMagick media class. It is pending a refactor of TilePicParser class to use this feature.

With a bit of refactor, new class `CommandConfiguration` can be promoted to `BaseMediaPlugin` class, and the feature will be available to subclasses.

### CODE REVIEW

**Comment by miceno** [comment]
I am afraid I made something wrong rebasing from upstream develop branch...

Do you think I should create a new PR cleaning the code?

**Comment by collectiveaccess** [comment]
What is wrong?

**Comment by miceno** [comment]
There are more changes in the PR than those from my initial branch, see changed files. I think I rebased using upstream develop and it included more commits.

**Comment by collectiveaccess** [comment]
Yes, please resubmit. Thanks!

**Pull request closed without merging**
