### PR TITLE
Show max upload limit on every file upload.

### PR DESCRIPTION
**Pull request by miceno**
Additionally refactor code and move formatting function to utility helpers.

### CODE REVIEW

**Comment by collectiveaccess** [comment]
This is a lot of text to add... how does it look when you try it?

**Comment by miceno** [comment]
Long, but I think a user needs the long tail to understand it. I hereby attach a screenshot.

image

**Comment by miceno** [comment]
I had to upload a 180Mb file and the configuration in php.ini was below that, so the request uploaded the file, but it silently complained later, with a CSRF Invalid Token error.

I would not have uploaded the file is I had known in advance the size limit, so I thought adding the text with the limits will help other users too.

**Comment by collectiveaccess** [comment]
It's way too long, but let's merge it and see how we can make it shorter later.

**Pull request merged**
