### PR TITLE
Validate redirect url onl login

### PR DESCRIPTION
**Pull request by SethKaufman**
PR adds checks to ensure that redirect URL passed to login process is local to server, preventing redirect to arbitrary urls. Thanks to @noobpk for report.

### CODE REVIEW

**Comment by noobpk** [comment]
Hi. I found your product on [cve details](https://www.cvedetails.com/product-list/vendor_id-12958/Collectiveaccess.html). Don't know if you can assign cve the vulnerabilities I've found.

**Comment by collectiveaccess** [comment]
We don't maintain a list on that site.

**Comment by noobpk** [comment]
ohh. So what about on [cve miter](https://cve.mitre.org). If not, I'll wait at the [hunter](https://huntr.dev) hihi

**Comment by collectiveaccess** [comment]
We'll take a look.

**Comment by noobpk** [comment]
Thank you very much.

**Comment by collectiveaccess** [comment]
Thank you for raising these issues so we could resolve them!

**Pull request merged**
